name: 1-Checkout-Build-Artifact

# This workflow will checkout the code, build the DotNet app, and create an artifact from the BIN folder for use in following workflows.
# For best scan results, we are using a Windows-2022 image to build the .Net code.
on:
  # Enables manual runs
  workflow_dispatch:
  schedule:
    # Runs "Every day ay 6:05" (see https://crontab.guru)
    - cron: '5 6 * * *'
jobs:
  Checkout-Build-Artifact:
    runs-on: windows-2022
    steps:

# Checkout code
    - uses: actions/checkout@v3

# Setup the .Net environment    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

# Build the .Net applications    
    - name: Build App
      run: dotnet publish app -c Debug /p:WebPublishMethod=Package /p:PackageLocation="../"

# Download Veracode
    - name: Download Veracode
      run: |
         curl -sSO https://tools.veracode.com/integrations/API-Wrappers/CSharp/bin/VeracodeCSharpAPI.zip
         unzip VeracodeCSharpAPI.zip VeracodeC#API.exe
         dir

# Submit to Veracode SAST/SCA Policy Scan    
    - name: Submit to Veracode SAST/SCA Policy Scan
      env: 
         VERACODE_API_ID: ${{ secrets.VERACODE_API_ID }}
         VERACODE_API_KEY: ${{ secrets.VERACODE_API_KEY }}
      run: >
         ./VeracodeC#API.exe -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }}
         -action uploadandscan
         -appname SN-VeraDemo-DotNetCore-GitHub 
         -createprofile true
         -version ${{ github.run_id }}
         -filepath app.zip
         -teams ClintPollock-DemoApps2023 

# Use the UploadAndScan action to submit the artifact for scanning for Sandbox       
    - name: Submit to Veracode SAST/SCA Sandbox scan
      env: 
         VERACODE_API_ID: ${{ secrets.VERACODE_API_ID }}
         VERACODE_API_KEY: ${{ secrets.VERACODE_API_KEY }}
      run: >
         ./VeracodeC#API.exe -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }}
         -action uploadandscan
         -appname SN-VeraDemo-DotNetCore-GitHub 
         -createprofile true
         -version ${{ github.run_id }}
         -filepath app.zip
         -teams ClintPollock-DemoApps2023 
         -createsandbox true
         -sandboxname DailyBuild
         

# Workflow to run SCA Agent Scan
  SCA-Advanced-Scan:
    runs-on: ubuntu-latest
    steps:    
# Checkout code
    - uses: actions/checkout@v3
    - name: SCA Advanced Scan of Repo
      env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
          Set-ExecutionPolicy AllSigned -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
          srcclr scan app --allow-dirty

    - name: SCA Agent Scan of Container
      env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
          Set-ExecutionPolicy AllSigned -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
          srcclr -s scan --image veracodedemolabs/verademo-dotnetcore-github:latest

# Workflow to run DAST Scan against QA server. 
  Submit-DAST-Scan:
    runs-on: ubuntu-latest
    steps:            
# Checkout
      - uses: actions/checkout@v2
      
# Update the DAST Scan Name to be uniuqe using SED command         
      - name: Update DAST config file with uniuqe scan name
        run: |
         NOW=$(date +"%m-%d-%Y-%T")
         sed -i 's/VeraDemo-DotNetCore-GitHub/VeraDemo-DotNetCore-GitHub-'${NOW}'/g' vc-dast-config.json

# Visual confirmation of the scan submission details
      - name: Display DAST config file with uniuqe scan name
        run: |
          cat vc-dast-config.json
 
# DAST scan submission using the DAST API 
      - name: Submit Veracode DAST Scan
        run: |
         pip install veracode-api-signing
         export VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}
         export VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}
         http --verbose --auth-type=veracode_hmac POST "https://api.veracode.com/was/configservice/v1/analyses?job_options=run_verification=false" < vc-dast-config.json
