name: 1-Checkout-Build-Artifact

# This workflow will checkout the code, build the DotNet app, and create an artifact from the BIN folder for use in following workflows.
# For best scan results, we are using a Windows-2022 image to build the .Net code.
on:
  # Enables manual runs
  workflow_dispatch:
  schedule:
    # Runs "Every day ay 6:05" (see https://crontab.guru)
    - cron: '5 6 * * *'
jobs:
  Checkout-Build-Artifact:
    runs-on: windows-2022
    steps:

# Checkout code
    - uses: actions/checkout@v3

# Setup the .Net environment    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

# Build the .Net applications    
    - name: Build App
      run: dotnet publish app -c Debug /p:WebPublishMethod=Package /p:PackageLocation="../../"

# SAST and SCA scan with Veracode
    - name: Download Veracode
      run: |
         curl -sSO https://tools.veracode.com/integrations/API-Wrappers/CSharp/bin/VeracodeCSharpAPI.zip
         unzip VeracodeCSharpAPI.zip VeracodeC#API.exe
         dir
       
    - name: Submit to Veracode
      env: 
         VERACODE_API_ID: ${{ secrets.VERACODE_API_ID }}
         VERACODE_API_KEY: ${{ secrets.VERACODE_API_KEY }}
      run: >
         ./VeracodeC#API.exe -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }}
         -action uploadandscan
         -appname SN-VeraDemo-DotNetCore-GitHub 
         -createprofile true
         -version ${{ github.run_id }}
         -filepath app.zip
         -teams ClintPollock-DemoApps2023 

# Running Software Composition Analysis Agent against the local repo while on a Windows machine since this is ASPDotNet

    - name: SCA Agent Scan of Repo
      env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
          Set-ExecutionPolicy AllSigned -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
          srcclr scan --allow-dirty

